# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.input_bar.setGeometry(QtCore.QRect(12, 480, 691, 41))
        self.input_bar.setStyleSheet("border: 2px solid rgb(193, 237, 238);\n"
"border-radius: 10px; ")
        self.input_bar.setObjectName("input_bar")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(710, 480, 81, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_send.setFont(font)
        self.btn_send.setStyleSheet("background-color: rgb(58, 249, 10);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_send.setObjectName("btn_send")
        self.output_screen = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_screen.setGeometry(QtCore.QRect(15, 11, 771, 461))
        self.output_screen.setStyleSheet("border: 2px solid rgb(175, 175, 175);")
        self.output_screen.setObjectName("output_screen")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Room"))
        self.btn_send.setText(_translate("MainWindow", "send"))
        self.btn_send.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
