# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvenOdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(567, 769)
        mainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 200, 531, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_browser_even = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.text_browser_even.setObjectName("text_browser_even")
        self.horizontalLayout.addWidget(self.text_browser_even)
        self.text_browser_odd = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.text_browser_odd.setObjectName("text_browser_odd")
        self.horizontalLayout.addWidget(self.text_browser_odd)
        self.odd_stop = QtWidgets.QPushButton(self.centralwidget)
        self.odd_stop.setGeometry(QtCore.QRect(430, 140, 100, 50))
        self.odd_stop.setObjectName("odd_stop")
        self.odd_start = QtWidgets.QPushButton(self.centralwidget)
        self.odd_start.setGeometry(QtCore.QRect(320, 140, 100, 50))
        self.odd_start.setObjectName("odd_start")
        self.even_start = QtWidgets.QPushButton(self.centralwidget)
        self.even_start.setGeometry(QtCore.QRect(30, 140, 100, 50))
        self.even_start.setObjectName("even_start")
        self.even_stop = QtWidgets.QPushButton(self.centralwidget)
        self.even_stop.setGeometry(QtCore.QRect(150, 140, 100, 50))
        self.even_stop.setObjectName("even_stop")
        self.spinbox_odd = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_odd.setGeometry(QtCore.QRect(440, 110, 91, 21))
        self.spinbox_odd.setObjectName("spinbox_odd")
        self.odd_label = QtWidgets.QLabel(self.centralwidget)
        self.odd_label.setGeometry(QtCore.QRect(310, 80, 125, 79))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.odd_label.setFont(font)
        self.odd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.odd_label.setObjectName("odd_label")
        self.even_label = QtWidgets.QLabel(self.centralwidget)
        self.even_label.setGeometry(QtCore.QRect(20, 80, 131, 79))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.even_label.setFont(font)
        self.even_label.setAlignment(QtCore.Qt.AlignCenter)
        self.even_label.setObjectName("even_label")
        self.spinbox_even = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_even.setGeometry(QtCore.QRect(160, 110, 91, 21))
        self.spinbox_even.setObjectName("spinbox_even")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 260, 79))
        font = QtGui.QFont()
        font.setPointSize(29)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 261, 79))
        font = QtGui.QFont()
        font.setPointSize(29)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Even Odd Displayer"))
        self.odd_stop.setText(_translate("mainWindow", "Stop"))
        self.odd_start.setText(_translate("mainWindow", "Start"))
        self.even_start.setText(_translate("mainWindow", "Start"))
        self.even_stop.setText(_translate("mainWindow", "Stop"))
        self.odd_label.setText(_translate("mainWindow", "Odd Frequency:"))
        self.even_label.setText(_translate("mainWindow", "Even Frequency:"))
        self.label_3.setText(_translate("mainWindow", "Display Odd"))
        self.label_4.setText(_translate("mainWindow", "Display Even"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
