# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(0, 91, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setAutoFillBackground(False)
        self.btn_clear.setStyleSheet("color: rgb(7, 8, 6);\n"
"background-color: rgb(239, 227, 193);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_neg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_neg.setGeometry(QtCore.QRect(80, 91, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_neg.setFont(font)
        self.btn_neg.setAutoFillBackground(False)
        self.btn_neg.setStyleSheet("color: rgb(7, 8, 6);\n"
"background-color: rgb(239, 227, 193);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_neg.setObjectName("btn_neg")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(240, 91, 80, 80))
        self.btn_div.setAutoFillBackground(False)
        self.btn_div.setStyleSheet("background-color: rgb(246, 170, 11);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_div.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Gui/UI/icon/division.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_div.setIcon(icon)
        self.btn_div.setIconSize(QtCore.QSize(25, 25))
        self.btn_div.setObjectName("btn_div")
        self.btn_mod = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mod.setGeometry(QtCore.QRect(160, 91, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mod.setFont(font)
        self.btn_mod.setAutoFillBackground(False)
        self.btn_mod.setStyleSheet("color: rgb(7, 8, 6);\n"
"background-color: rgb(239, 227, 193);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_mod.setObjectName("btn_mod")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(240, 171, 80, 80))
        self.btn_mult.setAutoFillBackground(False)
        self.btn_mult.setStyleSheet("background-color: rgb(246, 170, 11);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_mult.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Gui/UI/icon/multiply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mult.setIcon(icon1)
        self.btn_mult.setIconSize(QtCore.QSize(22, 22))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 171, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setAutoFillBackground(False)
        self.btn_1.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(160, 171, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setAutoFillBackground(False)
        self.btn_3.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_3.setObjectName("btn_3")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(80, 171, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setAutoFillBackground(False)
        self.btn_2.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_2.setObjectName("btn_2")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(240, 251, 80, 80))
        self.btn_minus.setAutoFillBackground(False)
        self.btn_minus.setStyleSheet("background-color: rgb(246, 170, 11);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_minus.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Gui/UI/icon/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minus.setIcon(icon2)
        self.btn_minus.setIconSize(QtCore.QSize(25, 25))
        self.btn_minus.setObjectName("btn_minus")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 251, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setAutoFillBackground(False)
        self.btn_4.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(160, 251, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setAutoFillBackground(False)
        self.btn_6.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(80, 251, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setAutoFillBackground(False)
        self.btn_5.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_5.setObjectName("btn_5")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(240, 331, 80, 80))
        self.btn_add.setAutoFillBackground(False)
        self.btn_add.setStyleSheet("background-color: rgb(246, 170, 11);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_add.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Gui/UI/icon/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon3)
        self.btn_add.setIconSize(QtCore.QSize(25, 25))
        self.btn_add.setObjectName("btn_add")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 331, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setAutoFillBackground(False)
        self.btn_7.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_7.setObjectName("btn_7")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(160, 331, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setAutoFillBackground(False)
        self.btn_9.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_9.setObjectName("btn_9")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(80, 331, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setAutoFillBackground(False)
        self.btn_8.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_8.setObjectName("btn_8")
        self.btn_dot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dot.setGeometry(QtCore.QRect(160, 411, 80, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dot.setFont(font)
        self.btn_dot.setAutoFillBackground(False)
        self.btn_dot.setStyleSheet("color: rgb(7, 8, 6);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_dot.setObjectName("btn_dot")
        self.btn_eq = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eq.setGeometry(QtCore.QRect(240, 411, 80, 80))
        self.btn_eq.setAutoFillBackground(False)
        self.btn_eq.setStyleSheet("background-color: rgb(246, 170, 11);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_eq.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Gui/UI/icon/equal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eq.setIcon(icon4)
        self.btn_eq.setIconSize(QtCore.QSize(22, 22))
        self.btn_eq.setObjectName("btn_eq")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(0, 411, 160, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setAutoFillBackground(False)
        self.btn_0.setStyleSheet("color: rgb(8, 10, 8);\n"
"background-color: rgb(229, 229, 229);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.btn_0.setObjectName("btn_0")
        self.step_screen = QtWidgets.QListWidget(self.centralwidget)
        self.step_screen.setGeometry(QtCore.QRect(320, 10, 210, 480))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.step_screen.setFont(font)
        self.step_screen.setStyleSheet("\n"
"background-color: rgb(63, 60, 65);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.step_screen.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.step_screen.setObjectName("step_screen")
        self.output_screen = QtWidgets.QLabel(self.centralwidget)
        self.output_screen.setGeometry(QtCore.QRect(0, 10, 321, 80))
        font = QtGui.QFont()
        font.setFamily(".SF Compact Rounded")
        font.setPointSize(17)
        self.output_screen.setFont(font)
        self.output_screen.setStyleSheet("\n"
"background-color: rgb(63, 60, 65);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"")
        self.output_screen.setFrameShape(QtWidgets.QFrame.Box)
        self.output_screen.setText("")
        self.output_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.output_screen.setObjectName("output_screen")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btn_clear.setText(_translate("MainWindow", "Del"))
        self.btn_clear.setShortcut(_translate("MainWindow", "Backspace"))
        self.btn_neg.setText(_translate("MainWindow", "+/-"))
        self.btn_neg.setShortcut(_translate("MainWindow", "`"))
        self.btn_div.setShortcut(_translate("MainWindow", "/"))
        self.btn_mod.setText(_translate("MainWindow", "%"))
        self.btn_mod.setShortcut(_translate("MainWindow", "%"))
        self.btn_mult.setShortcut(_translate("MainWindow", "*"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_1.setShortcut(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_3.setShortcut(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_2.setShortcut(_translate("MainWindow", "2"))
        self.btn_minus.setShortcut(_translate("MainWindow", "-"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_4.setShortcut(_translate("MainWindow", "4"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_6.setShortcut(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_5.setShortcut(_translate("MainWindow", "5"))
        self.btn_add.setShortcut(_translate("MainWindow", "+"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_7.setShortcut(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_9.setShortcut(_translate("MainWindow", "9"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_8.setShortcut(_translate("MainWindow", "8"))
        self.btn_dot.setText(_translate("MainWindow", "."))
        self.btn_dot.setShortcut(_translate("MainWindow", "."))
        self.btn_eq.setShortcut(_translate("MainWindow", "="))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_0.setShortcut(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
